# Generated by Django 4.2 on 2023-12-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mot', '0002_alter_mot_context_alter_mot_exemple_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mot',
            name='context',
            field=models.CharField(error_messages="Veuillez renseigner le contexte d'utilisation du mot", max_length=32),
        ),
    ]
